#!/usr/bin/env python3
"""Render the legal pages of the site from _build/legal.json.

Called at the end of build.py. Writes, for each language, an index and one page per
document, reusing the nav and the footer of that language's home page so they stay in
step without a second copy:

    legal/{,privacy/,terms/,copyright/}index.html        en
    it/legal/…                                           it
    es/legal/…                                           es

The text itself comes from the app (see fetch_legal.py): the site publishes it, the app
shows it when you sign up, and both read the same file.
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "_build")
SITE = "https://suonable.com"
DOCS = ("privacy", "terms", "copyright")
LANGS = (("en", "", "index.html"), ("it", "it/", "it/index.html"), ("es", "es/", "es/index.html"))

UI = {
    "en": {"legal": "Legal", "tagline": "The documents behind Suonable: what we do with your data, what "
                                        "you agree to, and how to report content you hold rights in.",
           "operator": "Operator", "stamp": "Version %s · updated %s", "read": "Read", "date": "%(d)d %(month)s %(y)d",
           "nav": {"privacy": "Privacy", "terms": "Terms", "copyright": "Copyright"},
           "contact": "Contact", "notices": "Copyright notices"},
    "it": {"legal": "Legale", "tagline": "I documenti dietro Suonable: cosa facciamo con i tuoi dati, cosa "
                                         "accetti e come segnalare contenuti di cui detieni i diritti.",
           "operator": "Operatore", "stamp": "Versione %s · aggiornata il %s", "read": "Leggi", "date": "%(d)02d/%(m)02d/%(y)d",
           "nav": {"privacy": "Privacy", "terms": "Termini", "copyright": "Copyright"},
           "contact": "Contatto", "notices": "Segnalazioni sul copyright"},
    "es": {"legal": "Legal", "tagline": "Los documentos detrás de Suonable: qué hacemos con tus datos, qué "
                                        "aceptas y cómo reclamar contenido del que tienes los derechos.",
           "operator": "Operador", "stamp": "Versión %s · actualizada el %s", "read": "Leer", "date": "%(d)02d/%(m)02d/%(y)d",
           "nav": {"privacy": "Privacidad", "terms": "Condiciones", "copyright": "Copyright"},
           "contact": "Contacto", "notices": "Avisos de copyright"},
}


MONTHS_EN = ("January", "February", "March", "April", "May", "June", "July",
             "August", "September", "October", "November", "December")


EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+[\w]")


def esc(s):
    return html.escape(s, quote=False)


def text(s):
    """Escaped, with the addresses the documents quote turned into links."""
    return EMAIL.sub(lambda m: '<a href="mailto:%s">%s</a>' % (m.group(0), m.group(0)), esc(s))


def stamp(lang, data):
    """Version and date, written the way that language writes dates."""
    y, m, d = (int(x) for x in data["updated"].split("-"))
    when = UI[lang]["date"] % {"d": d, "m": m, "y": y, "month": MONTHS_EN[m - 1]}
    return UI[lang]["stamp"] % (data["version"], when)


def chrome(lang, prefix, source, doc):
    """The nav and the footer of that language's home page, pointed back at it."""
    page = open(os.path.join(ROOT, source), encoding="utf-8").read()
    nav = page[page.index('<nav class="site-nav"'):page.index("</nav>") + len("</nav>")]
    foot = page[page.index("<footer"):page.index("</footer>") + len("</footer>")]
    home = "/" + prefix
    nav = nav.replace('href="#', 'href="%s#' % home)                       # anchors live on the home page
    for code, other, _ in LANGS:                                           # language links stay on this document
        nav = re.sub(r'(class="lang-btn" href=")[^"]*(" hreflang="%s")' % code,
                     r"\g<1>/%slegal/%s\g<2>" % (other, (doc + "/") if doc else ""), nav)
    return nav, foot


def head(lang, prefix, doc, title, description):
    path = "/%slegal/%s" % (prefix, (doc + "/") if doc else "")
    alts = "".join(
        '\n<link rel="alternate" hreflang="%s" href="%s/%slegal/%s">'
        % (code, SITE, other, (doc + "/") if doc else "") for code, other, _ in LANGS)
    alts += '\n<link rel="alternate" hreflang="x-default" href="%s/legal/%s">' % (SITE, (doc + "/") if doc else "")
    return f"""<!DOCTYPE html>
<!-- Generated by _build/legal_pages.py from _build/legal.json — do not edit by hand. -->
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} — Suonable</title>
<meta name="description" content="{html.escape(description[:180], quote=True)}">
<link rel="canonical" href="{SITE}{path}">{alts}
<link rel="icon" type="image/svg+xml" href="/suonable-mark-flat.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<meta name="theme-color" content="#1055AD">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800;900&amp;family=JetBrains+Mono:wght@400;700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="/styles.css?v=33">
<script src="/app.js?v=21" defer></script>
</head>
<body>

<div style="padding: 18px clamp(14px, 3vw, 40px) 0;">
"""


def switcher(lang, prefix, current, data):
    ui, out = UI[lang], []
    for doc in DOCS:
        label = esc(ui["nav"][doc])
        href = "/%slegal/%s/" % (prefix, doc)
        cls = "legal-tab is-current" if doc == current else "legal-tab"
        out.append('<a class="%s" href="%s"%s>%s</a>' % (cls, href, ' aria-current="page"' if doc == current else "", label))
    return '<nav class="legal-tabs" aria-label="%s">%s</nav>' % (esc(ui["legal"]), "".join(out))


def operator_card(lang, data):
    ui, op = UI[lang], data["operator"]
    return f"""<aside class="legal-operator">
        <div class="legal-operator-label">{esc(ui['operator'])}</div>
        <p><b>{esc(op['name'])}</b><br>{esc(op['address'])}, {esc(data.get('country', {}).get(lang) or op['country'])}<br>{esc(op['taxLabel'])} {esc(op['taxId'])}</p>
        <p>{esc(ui['contact'])}: <a href="mailto:{op['contact']}">{op['contact']}</a><br>
           {esc(ui['notices'])}: <a href="mailto:{op['abuse']}">{op['abuse']}</a></p>
      </aside>"""


def document_page(lang, prefix, source, doc, data):
    ui, d = UI[lang], data["langs"][lang][doc]
    nav, foot = chrome(lang, prefix, source, doc)
    body = []
    for section in d["sections"]:
        body.append("<h2>%s</h2>" % esc(section["h"]))
        body.extend("<p>%s</p>" % text(p) for p in section["p"])
    return (head(lang, prefix, doc, d["title"], d["intro"]) + nav + """

<main class="legal">
  <div class="legal-inner">
    <div class="legal-eyebrow">%s</div>
    <h1>%s</h1>
    <p class="legal-stamp">%s</p>
    %s
    <article class="legal-body">
      <p class="legal-intro">%s</p>
      %s
    </article>
    %s
  </div>
</main>

%s

</div>

</body>
</html>
""" % (esc(ui["legal"]), esc(d["title"]), esc(stamp(lang, data)),
       switcher(lang, prefix, doc, data), text(d["intro"]), "\n      ".join(body),
       operator_card(lang, data), foot))


def index_page(lang, prefix, source, data):
    ui = UI[lang]
    nav, foot = chrome(lang, prefix, source, "")
    cards = []
    for doc in DOCS:
        d = data["langs"][lang][doc]
        cards.append("""<a class="legal-card" href="/%slegal/%s/">
        <h2>%s</h2>
        <p>%s</p>
        <span class="legal-card-go">%s →</span>
      </a>""" % (prefix, doc, esc(d["title"]), esc(d["intro"]), esc(ui["read"])))
    return (head(lang, prefix, "", ui["legal"], ui["tagline"]) + nav + """

<main class="legal">
  <div class="legal-inner">
    <h1>%s</h1>
    <p class="legal-stamp">%s</p>
    <p class="legal-lede">%s</p>
    <div class="legal-cards">
      %s
    </div>
    %s
  </div>
</main>

%s

</div>

</body>
</html>
""" % (esc(ui["legal"]), esc(stamp(lang, data)),
       esc(ui["tagline"]), "\n      ".join(cards), operator_card(lang, data), foot))


def apply_overlay(data):
    """Corrections the site publishes on top of the app's text (see legal_overlay.json)."""
    path = os.path.join(BUILD, "legal_overlay.json")
    if not os.path.exists(path):
        return
    overlay = json.load(open(path, encoding="utf-8"))
    data["operator"].update(overlay.get("operator", {}))
    # corrections the app does not carry yet make this a later version of the documents
    for field in ("version", "updated"):
        if field in overlay:
            data[field] = overlay[field]

    for swap in overlay.get("swaps", []):
        hits = 0
        for docs in data["langs"].values():
            doc = docs[swap["doc"]]
            doc["intro"] = doc["intro"].replace(swap["from"], swap["to"])
            for sec in doc["sections"]:
                hits += sum(x.count(swap["from"]) for x in sec["p"])
                sec["p"] = [x.replace(swap["from"], swap["to"]) for x in sec["p"]]
        if not hits:
            print("  overlay: %s no longer appears in %s — the app may have changed it"
                  % (swap["from"], swap["doc"]))

    paragraph_ops = [e for e in overlay["edits"] if e["op"] != "section"]
    section_ops = sorted((e for e in overlay["edits"] if e["op"] == "section"),
                         key=lambda e: e["after"], reverse=True)          # late inserts first, indexes hold

    for edit in paragraph_ops:
        for lang, docs in data["langs"].items():
            doc = docs[edit["doc"]]
            if edit["op"] == "intro":
                doc["intro"] = edit["text"][lang]
                continue
            section = doc["sections"][edit["section"]]
            if edit["op"] == "replace":
                if lang == "en" and edit.get("was", "") not in section["p"][edit["paragraph"]]:
                    print("  overlay: %s section %d no longer reads as expected — check the app"
                          % (edit["doc"], edit["section"]))
                section["p"][edit["paragraph"]] = edit["text"][lang]
            elif edit["op"] == "append":
                section["p"].append(edit["text"][lang])
            elif edit["op"] == "prepend":
                section["p"].insert(0, edit["text"][lang])

    for edit in section_ops:
        for lang, docs in data["langs"].items():
            docs[edit["doc"]]["sections"].insert(
                edit["after"] + 1, {"h": edit["h"][lang], "p": [x[lang] for x in edit["p"]]})

    print("  overlay: %d corrections applied over the app's text" % len(overlay["edits"]))


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(text)


def build():
    data = json.load(open(os.path.join(BUILD, "legal.json"), encoding="utf-8"))
    apply_overlay(data)
    pages = []
    for lang, prefix, source in LANGS:
        write("%slegal/index.html" % prefix, index_page(lang, prefix, source, data))
        pages.append("/%slegal/" % prefix)
        for doc in DOCS:
            write("%slegal/%s/index.html" % (prefix, doc), document_page(lang, prefix, source, doc, data))
            pages.append("/%slegal/%s/" % (prefix, doc))
    add_to_sitemap(pages)
    print("wrote %d legal pages" % len(pages))


def add_to_sitemap(paths):
    path = os.path.join(ROOT, "sitemap.xml")
    xml = open(path, encoding="utf-8").read()
    xml = re.sub(r"  <url>\n    <loc>[^<]*/legal/[^<]*</loc>\n  </url>\n", "", xml)   # rerunnable
    entries = "".join("  <url>\n    <loc>%s%s</loc>\n  </url>\n" % (SITE, p) for p in paths)
    open(path, "w", encoding="utf-8").write(xml.replace("</urlset>", entries + "</urlset>"))


if __name__ == "__main__":
    build()
